#!/usr/bin/env python3
"""
Launcher icon generator shared by the Paris and Sofia apps.

Base glyph (identical in both apps): a departure-board card with two rows.
City marker: a bold letter tag in the bottom-right corner (P = Paris, S = Sofia),
drawn from DejaVu Sans Bold outlines so both letters match. Everything sits inside
the 66 dp adaptive-icon safe zone (circle of radius 33 around 54,54).

Usage: python3 gen_icon.py <letter> <bg-hex> <res-dir> <out-png-512> [preview-png]
Writes: drawable/ic_launcher_foreground.xml, drawable/ic_launcher_monochrome.xml,
        drawable/ic_city_tag.xml, values/launcher_colors.xml, the 512 px PNG,
        and optionally a contact sheet (color, masks, themed light/dark).
"""
import io, os, sys
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.boundsPen import BoundsPen

FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"

INK = "#15171B"
CARD = "#FBFAF7"
ORANGE = "#F28E1C"
BROWN = "#8D653D"
GREEN = "#0B8A5A"
GREY = "#8C9198"

TAG_C = (67.0, 67.0)   # tag centre
TAG_R = 12.5           # tag radius (inside the 33 dp safe radius: 18.4 + 12.5 = 30.9)
RING_R = 15.0          # gap ring cut out of the card around the tag
GLYPH_H = 13.5         # letter cap height


def rr(x0, y0, x1, y1, r):
    return (f"M{x0+r},{y0} H{x1-r} A{r},{r} 0 0 1 {x1},{y0+r} V{y1-r} A{r},{r} 0 0 1 {x1-r},{y1} "
            f"H{x0+r} A{r},{r} 0 0 1 {x0},{y1-r} V{y0+r} A{r},{r} 0 0 1 {x0+r},{y0} Z")


def circle(cx, cy, r):
    return f"M{cx-r},{cy} A{r},{r} 0 1 0 {cx+r},{cy} A{r},{r} 0 1 0 {cx-r},{cy} Z"


def glyph_path(letter):
    f = TTFont(FONT)
    gs = f.getGlyphSet()
    name = f.getBestCmap()[ord(letter)]
    bp = BoundsPen(gs)
    gs[name].draw(bp)
    xmin, ymin, xmax, ymax = bp.bounds
    s = GLYPH_H / (ymax - ymin)
    w = (xmax - xmin) * s
    tx = TAG_C[0] - w / 2 - xmin * s + 0.3   # optical nudge right
    ty = TAG_C[1] + GLYPH_H / 2 + ymin * s
    sp = SVGPathPen(gs, ntos=lambda v: f"{v:.2f}")
    gs[name].draw(TransformPen(sp, (s, 0, 0, -s, tx, ty)))
    return sp.getCommands()


CARD_P = rr(28, 31, 76, 71, 6)
ROWS = {
    "badge1": (rr(33, 37, 43, 44, 2), ORANGE),
    "bar1": (rr(47, 38.5, 62, 42.5, 1.2), INK),
    "dot1": (circle(68, 40.5, 2.6), GREEN),
    "badge2": (rr(33, 49, 43, 56, 2), BROWN),
    "bar2": (rr(47, 50.5, 55, 54.5, 1.2), GREY),
}


def layers(letter, bg):
    g = glyph_path(letter)
    fg = [
        (CARD_P, CARD, "nonZero"),
        *[(p, c, "nonZero") for p, c in ROWS.values()],
        (circle(*TAG_C, RING_R), bg, "nonZero"),
        (circle(*TAG_C, TAG_R), INK, "nonZero"),
        (g, "#FFFFFF", "nonZero"),
    ]
    # Monochrome: (card minus rows minus ring, clipped to the card) + (tag minus letter).
    mono = (" ".join([CARD_P, *[p for p, _ in ROWS.values()], circle(*TAG_C, RING_R)]),
            " ".join([circle(*TAG_C, TAG_R), g]))
    tag = [(circle(12, 12, 11.5), INK, "nonZero"), (g, "#FFFFFF", "nonZero")]
    return fg, mono, g


def vector_xml(paths, size_dp=108, viewport=108, comment=""):
    out = [f'<?xml version="1.0" encoding="utf-8"?>',
           f'<!-- Generated by tools/icon/gen_icon.py. {comment} -->',
           f'<vector xmlns:android="http://schemas.android.com/apk/res/android"',
           f'    android:width="{size_dp}dp" android:height="{size_dp}dp"',
           f'    android:viewportWidth="{viewport}" android:viewportHeight="{viewport}">']
    for d, color, rule in paths:
        fc = "#FF" + color.lstrip("#").upper() if len(color) == 7 else color
        out.append(f'    <path android:fillColor="{fc}" android:fillType="{rule}"\n        android:pathData="{d}" />')
    out.append("</vector>")
    return "\n".join(out) + "\n"


def mono_xml(mono):
    card, tag = mono
    return (f'<?xml version="1.0" encoding="utf-8"?>\n'
            f'<!-- Generated by tools/icon/gen_icon.py. Themed-icon layer (Android 13+): tinted by the system, letter tag included. -->\n'
            f'<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            f'    android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">\n'
            f'    <group>\n'
            f'        <!-- Clip to the card so the ring cut-out only removes card, never adds outside it. -->\n'
            f'        <clip-path android:pathData="{CARD_P}" />\n'
            f'        <path android:fillColor="#FF000000" android:fillType="evenOdd"\n            android:pathData="{card}" />\n'
            f'    </group>\n'
            f'    <path android:fillColor="#FF000000" android:fillType="evenOdd"\n        android:pathData="{tag}" />\n'
            f'</vector>\n')


def tag_xml(letter):
    # Same letter outline, re-centred in a 24-unit viewport for the widget-picker preview.
    g = glyph_path(letter)
    return vector_xml([(circle(67, 67, 11.5), INK, "nonZero"), (g, "#FFFFFF", "nonZero")],
                      size_dp=24, viewport=24, comment=f"City tag '{letter}'.").replace(
        'android:viewportWidth="24" android:viewportHeight="24">',
        'android:viewportWidth="24" android:viewportHeight="24">\n    <group android:translateX="-55" android:translateY="-55">'
    ).replace("</vector>", "    </group>\n</vector>")


def svg(fg_paths, bg, size=512, mask=None, mono=None, mono_fg=None, mono_bg=None):
    s = size / 108
    clip = ""
    if mask == "circle":
        clip = f'<clipPath id="m"><circle cx="54" cy="54" r="36"/></clipPath>'
    elif mask == "squircle":
        clip = f'<clipPath id="m"><path d="{rr(18,18,90,90,22)}"/></clipPath>'
    body = []
    if mono is not None:
        body.append(f'<rect width="108" height="108" fill="{mono_bg}"/>')
        body.append(f'<clipPath id="card"><path d="{CARD_P}"/></clipPath>')
        body.append(f'<path d="{mono[0]}" fill="{mono_fg}" fill-rule="evenodd" clip-path="url(#card)"/>')
        body.append(f'<path d="{mono[1]}" fill="{mono_fg}" fill-rule="evenodd"/>')
    else:
        body.append(f'<rect width="108" height="108" fill="{bg}"/>')
        for d, c, rule in fg_paths:
            body.append(f'<path d="{d}" fill="{c}" fill-rule="{"evenodd" if rule == "evenOdd" else "nonzero"}"/>')
    g = "".join(body)
    if mask:
        g = f'<g clip-path="url(#m)">{g}</g>'
    vb = "18 18 72 72" if mask else "0 0 108 108"   # launchers show the central 72 dp
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{size}" height="{size}" viewBox="{vb}">'
            f'<defs>{clip}</defs>{g}</svg>')


def main():
    letter, bg, res, png512 = sys.argv[1:5]
    preview = sys.argv[5] if len(sys.argv) > 5 else None
    import cairosvg
    fg, mono, _ = layers(letter, bg)
    os.makedirs(f"{res}/drawable", exist_ok=True)
    os.makedirs(f"{res}/values", exist_ok=True)
    open(f"{res}/drawable/ic_launcher_foreground.xml", "w").write(vector_xml(fg, comment=f"Base card + '{letter}' tag."))
    open(f"{res}/drawable/ic_launcher_monochrome.xml", "w").write(mono_xml(mono))
    open(f"{res}/drawable/ic_city_tag.xml", "w").write(tag_xml(letter))
    open(f"{res}/values/launcher_colors.xml", "w").write(
        f'<?xml version="1.0" encoding="utf-8"?>\n<resources>\n    <color name="launcher_bg">#FF{bg.lstrip("#").upper()}</color>\n</resources>\n')
    cairosvg.svg2png(bytestring=svg(fg, bg, 512).encode(), write_to=png512)
    if preview:
        from PIL import Image
        tiles = []
        for b, l, label in [(bg, letter, letter), ("#BD202E", "S", "S")]:
            f2, m2, _ = layers(l, b)
            for kind in ["circle", "squircle", "mono-light", "mono-dark"]:
                if kind.startswith("mono"):
                    fgc, bgc = ("#2B4A5E", "#D7E6F2") if kind == "mono-light" else ("#C9DDEC", "#1E2A33")
                    sv = svg(f2, b, 192, "circle", mono=m2, mono_fg=fgc, mono_bg=bgc)
                else:
                    sv = svg(f2, b, 192, kind)
                tiles.append(Image.open(io.BytesIO(cairosvg.svg2png(bytestring=sv.encode()))))
                small = cairosvg.svg2png(bytestring=sv.encode(), output_width=48, output_height=48)
                tiles.append(Image.open(io.BytesIO(small)))
        sheet = Image.new("RGBA", (4 * (192 + 48 + 40) + 20, 2 * 212 + 20), (120, 120, 120, 255))
        for row in range(2):
            for col in range(4):
                big, sm = tiles[(row * 4 + col) * 2], tiles[(row * 4 + col) * 2 + 1]
                x = 20 + col * (192 + 48 + 40)
                y = 20 + row * 212
                sheet.paste(big, (x, y), big)
                sheet.paste(sm, (x + 192 + 10, y + 144), sm)
        sheet.save(preview)


if __name__ == "__main__":
    main()
